# Generated by Django 5.0.2 on 2024-05-05 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('postalcode', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='place_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('relaxation_type', models.CharField(blank=True, choices=[('Сімейний', 'Family'), ('Молодіжний', 'Youth'), ('Гірський', 'Mountain'), ('Екстримальний', 'Extreme'), ('SPA', 'Spa'), ('Заспокійливий', 'Calming'), ('Пасивний', 'Passive'), ('Активний', 'Active'), ('З водоймою', 'With Water'), ('На природі', 'Nature'), ('Пізнавальний', 'Cognitive'), ('З компанією', 'With Company'), ('Лікувально-оздоровчий', 'Medical')], max_length=30, null=True)),
                ('trip_goal', models.CharField(blank=True, choices=[('Розслабитися', 'Relaxation'), ('Насолодидись природою', 'Enjoy Nature'), ('Зробити гарні фото', 'Make Nice Photos'), ('Поплавати', 'Swim'), ('Відвідати музеї/замки', 'Visit Museums Castles'), ('Смачно поїсти', 'Eat Tasty'), ('Розважитися в клубі', 'Have Fun In Club'), ('Дізнатись щось нове', 'Learn Something New'), ('Покататись на лижах', 'Skiing'), ('Погуляти містом', 'Walk City')], max_length=50, null=True)),
                ('with_food', models.BooleanField(default=False)),
                ('with_sleep', models.BooleanField(default=False)),
                ('image', models.ManyToManyField(blank=True, default=None, related_name='places', to='place.image')),
                ('location', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='place.address')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='place',
            field=models.ManyToManyField(blank=True, related_name='images', to='place.place'),
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_favorite', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.place')),
            ],
        ),
    ]
