# Generated by Django 5.0.3 on 2024-04-12 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.address'),
        ),
    ]
