# Generated by Django 5.0.3 on 2024-04-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='place',
            field=models.ManyToManyField(related_name='images', to='place.place'),
        ),
    ]
