# Generated by Django 5.0.3 on 2024-04-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_image_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='image',
            field=models.ManyToManyField(related_name='places', to='place.image'),
        ),
    ]
