# Generated by Django 5.0.2 on 2024-04-13 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0003_alter_place_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='place.address'),
        ),
    ]
