# Generated by Django 5.0.3 on 2024-05-15 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0003_alter_history_place_alter_history_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.place'),
        ),
    ]
