# Generated by Django 5.0.3 on 2024-04-29 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0004_alter_tokenproxy_options'),
        ('place', '0003_place_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='user',
        ),
        migrations.AddField(
            model_name='history',
            name='token',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='authtoken.token'),
            preserve_default=False,
        ),
    ]
