# Generated by Django 5.0.3 on 2024-05-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0005_remove_history_token_history_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='with_food',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='place',
            name='with_sleep',
            field=models.BooleanField(default=False),
        ),
    ]
