# Generated by Django 5.0.3 on 2024-04-13 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0006_alter_place_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='relaxation_type',
            field=models.CharField(blank=True, choices=[('Сімейний', 'Family'), ('Молодіжний', 'Youth'), ('Гірський', 'Mountain'), ('Екстримальний', 'Extreme'), ('SPA', 'Spa'), ('Заспокійливий', 'Calming'), ('Пасивний', 'Passive'), ('Активний', 'Active'), ('З водоймою', 'With Water'), ('На природі', 'Nature'), ('Пізнавальний', 'Cognitive'), ('З компанією', 'With Company'), ('Лікувально-оздоровчий', 'Medical')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='trip_goal',
            field=models.CharField(blank=True, choices=[('Розслабитися', 'Relaxation'), ('Насолодидись природою', 'Enjoy Nature'), ('Зробити гарні фото', 'Make Nice Photos'), ('Поплавати', 'Swim'), ('Відвідати музеї/замки', 'Visit Museums Castles'), ('Смачно поїсти', 'Eat Tasty'), ('Розважитися в клубі', 'Have Fun In Club'), ('Дізнатись щось нове', 'Learn Something New'), ('Покататись на лижах', 'Skiing'), ('Погуляти містом', 'Walk City')], max_length=50, null=True),
        ),
    ]
