# Generated by Django 5.0.3 on 2024-05-16 08:06

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0006_alter_history_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='place_images/default photo.jpg', upload_to='place_images/'),
        ),
        migrations.AlterField(
            model_name='place',
            name='relaxation_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('FAMILY', 'Сімейний'), ('YOUTH', 'Молодіжний'), ('MOUNTAIN', 'Гірський'), ('EXTREME', 'Екстримальний'), ('SPA', 'SPA'), ('CALMING', 'Заспокійливий'), ('PASSIVE', 'Пасивний'), ('ACTIVE', 'Активний'), ('WITH_WATER', 'З водоймою'), ('NATURE', 'На природі'), ('COGNITIVE', 'Пізнавальний'), ('WITH_COMPANY', 'З компанією'), ('MEDICAL', 'Лікувально-оздоровчий'), ('CREATIVE', 'Творчий'), ('SHOPPING', 'Шопінг')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='trip_goal',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('RELAXATION', 'Розслабитися'), ('ENJOY_NATURE', 'Насолодидись природою'), ('MAKE_NICE_PHOTOS', 'Зробити гарні фото'), ('SWIM', 'Поплавати'), ('VISIT_MUSEUMS_CASTLES', 'Відвідати музеї/замки'), ('EAT_TASTY', 'Смачно поїсти'), ('HAVE_FUN', 'Розважитися'), ('LEARN_SOMETHING_NEW', 'Дізнатись щось нове'), ('SKIING', 'Покататись на лижах'), ('WALK_CITY', 'Погуляти містом')], max_length=255, null=True),
        ),
    ]
