# Generated by Django 5.0.3 on 2024-05-03 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0006_place_with_food_place_with_sleep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='places', to='place.image'),
        ),
    ]
