# Generated by Django 5.0.3 on 2024-05-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0007_alter_place_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='place',
            field=models.ManyToManyField(blank=True, related_name='images', to='place.place'),
        ),
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.ManyToManyField(blank=True, default=None, related_name='places', to='place.image'),
        ),
    ]
