# Generated by Django 5.0.3 on 2024-05-05 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0008_alter_image_place_alter_place_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default=1, upload_to='place_images/'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='image',
            name='place',
        ),
        migrations.RemoveField(
            model_name='place',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='place',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='place.place'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='place_images/'),
        ),
    ]
