# Generated by Django 5.0.3 on 2024-04-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0008_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
