# Generated by Django 5.0.3 on 2024-05-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0010_alter_place_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='image',
        ),
        migrations.AddField(
            model_name='place',
            name='slug',
            field=models.SlugField(default=2),
            preserve_default=False,
        ),
    ]
