# Generated by Django 5.0.3 on 2024-05-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0011_remove_place_image_place_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
