# Generated by Django 5.0.3 on 2024-05-06 21:14

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0012_alter_place_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='relaxation_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('FAMILY', 'Сімейний'), ('YOUTH', 'Молодіжний'), ('MOUNTAIN', 'Гірський'), ('EXTREME', 'Екстримальний'), ('SPA', 'SPA'), ('CALMING', 'Заспокійливий'), ('PASSIVE', 'Пасивний'), ('ACTIVE', 'Активний'), ('WITH_WATER', 'З водоймою'), ('NATURE', 'На природі'), ('COGNITIVE', 'Пізнавальний'), ('WITH_COMPANY', 'З компанією'), ('MEDICAL', 'Лікувально-оздоровчий')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='trip_goal',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('RELAXATION', 'Розслабитися'), ('YOUTH', 'Молодіжний'), ('MOUNTAIN', 'Гірський'), ('EXTREME', 'Екстримальний'), ('SPA', 'SPA'), ('CALMING', 'Заспокійливий'), ('PASSIVE', 'Пасивний'), ('ACTIVE', 'Активний'), ('WITH_WATER', 'З водоймою'), ('NATURE', 'На природі'), ('COGNITIVE', 'Пізнавальний'), ('WITH_COMPANY', 'З компанією'), ('MEDICAL', 'Лікувально-оздоровчий')], max_length=255, null=True),
        ),
    ]
